export const COURSE_FEATURE = 'COURSE_FEATURE';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
